### ISSUE TITLE
Root Issues with 8GB Pi, and System Info Wanted

### ISSUE THREAD

**Issue by BiboyLin** [pslade2/RealTimeKin#1]
Hello, Thanks for your work on OpenSenseRT first! I am trying to rebuild your RT system by following your instruction, for rehabilitation purposes.
However, after flashed your system image file to an SD card(32GB), the Raspberry Pi 4B couldn't boot with the issue shown in the following picture.

![image](https://user-images.githubusercontent.com/34125254/117312889-feae0e00-aeb7-11eb-84d1-b2c3df980063.png)

The error info was:
ERROR:00000044
start4.elf: is not compatible

Some people said this issue comes with the image conflict with firmware. I wonder whether it was due to my Raspberry version (I am using 8GB RAM type)? You mentioned in your paper that the 8GB Pi hasn't been tested.

By the way, which Ubuntu system version was used in your image? 
And besides the necessary operating system and the code and files in this Repository [(https://github.com/pslade2/RealTimeKin)](url) , what else files or code environment should be installed or added for Opensense RT system running?
Given such info, maybe I can contribute a system image for 8GB Pi.

Thanks!

**Comment by pslade2** [comment]
Hi Lin,

Glad you're trying to build it! I would highly recommend using a Raspberry Pi 4GB to avoid this issue because building everything yourself is quite challenging. That said, the unofficial set of instructions that I use to build OpenSim and install all necessary packages can be seen here: https://docs.google.com/document/d/1bGjWMoWRh_wkonu4updAyhID1Ui74cHq09XTrRmv-vo/edit?usp=sharing 

The Ubuntu system version I used was: Ubuntu 18.04.4 LTS  (GNU/Linux 5.3.0-1040-raspi2 aarch64)

**Comment by BiboyLin** [comment]
Thank you! After I tried in the 4GB Pi version, the operating system based on your system image provided worked! And I am still struggling in the IMU and iic script and setting(for I used the different type from you used).
Once I finish the 4GB build, I will try the 8GB version based your document!  Thanks again!

**Comment by pslade2** [comment]
Gotcha. Out of curiosity, which IMU are you using? I saw that the one I listed is out of stock right now due to the chip shortage. It should be quite easy to switch between these IMUs:  LSM6DSOX, ISM330DHC, & LSM6DSO32 which I am thinking about supporting all of them. In case that makes it easier for you, you could try those first rather than try other sensors because the i2c is definitely a challenge.

**Comment by BiboyLin** [comment]
Yep! Thank for your advice. But the I2C part is done, and I can read the IMU data in the my test code.
However, when I try the whole ik_streaming.py , the IMU data can not update and keep outputting a very large number like 20+ even during the calibration  Process. I am still struggling with this IMU data reading problem. I am using the IMU produced in China, whose model is Wit JY61P with the chip model is ICM42605.
The IMU data reading is self-coded as

import smbus
import time

def ReadIMU(IMUaddress):
    head_gyro = JY61P(IMUaddress)
    head_gyro.acceleration = head_gyro.get_acc()
    head_gyro.gyro = head_gyro.get_gyro()
    return head_gyro

class JY61P(object):
 
    def __init__(self, addr):
        self.addr = addr
        self.i2c = smbus.SMBus(1)
        self.acceleration = []
        self.gyro = []
 
    def get_acc(self):
        try:
            self.raw_acc_x = self.i2c.read_i2c_block_data(self.addr, 0x34, 2)
            self.raw_acc_y = self.i2c.read_i2c_block_data(self.addr, 0x35, 2)
            self.raw_acc_z = self.i2c.read_i2c_block_data(self.addr, 0x36, 2)
        except IOError:
            print("ReadError: gyro_acc")
            return (0, 0, 0)
        else:
            self.k_acc = 16 * 9.8
 
            self.acc_x = (self.raw_acc_x[1] << 8 | self.raw_acc_x[0]) / 32768 * self.k_acc
            self.acc_y = (self.raw_acc_y[1] << 8 | self.raw_acc_y[0]) / 32768 * self.k_acc
            self.acc_z = (self.raw_acc_z[1] << 8 | self.raw_acc_z[0]) / 32768 * self.k_acc
            if self.acc_x >= self.k_acc:
                self.acc_x -= 2 * self.k_acc 
        
            if self.acc_y >= self.k_acc:
               self.acc_y -= 2 * self.k_acc
                
            if self.acc_z >= self.k_acc:
                self.acc_z -= 2 * self.k_acc
            
            self.acceleration = [self.acc_x, self.acc_y, self.acc_z]
            return (self.acceleration)

    def get_gyro(self):
        try:
            self.raw_gyro_x = self.i2c.read_i2c_block_data(self.addr, 0x37, 2)
            self.raw_gyro_y = self.i2c.read_i2c_block_data(self.addr, 0x38, 2)
            self.raw_gyro_z = self.i2c.read_i2c_block_data(self.addr, 0x39, 2)
        except IOError:
            print("ReadError: gyro_gyro")
            return (0, 0, 0)
        else:
            self.k_gyro = 2000
            self.gyro_x = (self.raw_gyro_x[1] << 8 | self.raw_gyro_x[0]) / 32768 * self.k_gyro
            self.gyro_y = (self.raw_gyro_y[1] << 8 | self.raw_gyro_y[0]) / 32768 * self.k_gyro
            self.gyro_z = (self.raw_gyro_z[1] << 8 | self.raw_gyro_z[0]) / 32768 * self.k_gyro
 
            if self.gyro_x >= self.k_gyro:
                self.gyro_x -= 2 * self.k_gyro
        
            if self.gyro_y >= self.k_gyro:
               self.gyro_y -= 2 * self.k_gyro
                
            if self.gyro_z >= self.k_gyro:
                self.gyro_z -= 2 * self.k_gyro
            self.gyro = [self.gyro_x, self.gyro_y, self.gyro_z]
            return (self.gyro)

`

 I will be very appreciated if you can provide any suggestion?  

By the way, I am trying to realize the visualization by using the X11 forwarding tech to display the real-time IK result in the remote Mac controller. But failed with the 3D displaying with the error:

> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast 

Did you meet such problem? And I wonder how you achieve the display of IK result? 

Thanks a lot!

**Comment by BiboyLin** [comment]
For my IMU reading function and my edited workers you can see at [https://github.com/BiboyLin/RealTimeKin/tree/master](url) , which is JY61P.py and workers0.py

**Comment by pslade2** [comment]
Unfortunately we won't be able to support people using custom IMU code, due to those challenges. I'd suggest you break down the tests into their components. 1) Does the IMU read data correctly separate from the rest of the system. 2) Is the data formatted using the same units (I believe deg/s and m/s^2) and formatted appropriately in the ik_streaming file. 3) Are the messages passed between the worker and main file updating correctly at the rate you would like?

Also I have added support for the IMU models I mentioned before in case it is helpful to use those.

**Comment by BiboyLin** [comment]
Thanks for your advice! 
IMU data reading problem was solved now! However, the IK result was terrible
Here is my IK result showed in Opensim :


https://user-images.githubusercontent.com/34125254/121982627-68c4a780-cdc2-11eb-9f19-b0880a7d3037.mov



I still couldn't ensure which part was the problem: **Is the IMU data problem or IK processing problem?**

**For examing the IMU data, I have checked the 1) and 3) components you mentioned by :** 
1) **comparing with another type of IMU using the same walking condition** 
**Result:** The IMU and reading function can work well, the following picture was the raw imu recording of right foot (acc_x,acc_y,acc_z, gyro_x,gyro_y, gyro_z) produced by the ik_streaming, corresponding the IK result above, it seems correct comparing with another one used in my exoskeleton.
![image](https://user-images.githubusercontent.com/34125254/121981153-bee41b80-cdbf-11eb-81ee-ed1a9884dd32.png)

3) **comparing with 100hz and 30hz sampling rate**
**Result:**  I found the Pi can't process the data in 100Hz, which would lead to only approximately 1/3 data can be recorded in the .npy or .sto, for example, about 50s walking data, only 16s was recorded in the raw_imu_data.npy and 15s in the recording_x.sto

As for the 2nd component, can you provide some sample recording like walking data, so that I can comparing the format of my IMU data with yours?

Besides, I still interest in your visualization setting and how you achieve it?

Thanks again. And I want to start a new issue to continue with you~

**Comment by pslade2** [comment]
Answered in the new thread.
