### ISSUE TITLE
Root Issues with 4GB Pi

### ISSUE THREAD

**Issue by Khuramsha** [pslade2/RealTimeKin#3]
Hey there, I'm trying to rebuild your system with almost all the same components, but it seems like I'm stuck at the first step. I've followed your instructions and flashed the image file onto the sd card using balenaetcher and raspberry pi imager. But both times couldn't boot up. 
the picture below shows the error message
![boot](https://user-images.githubusercontent.com/35789828/130574153-78399c59-6e95-4b6f-ba8f-e510a3c4ca82.jpg)

Are you using raspberry pi 4 model b or just raspberry pi 4? (as it's shown in the pic, I'm using raspberry pi 4 model b 4GB)

**Comment by pslade2** [comment]
Hi there! It looks like you are using the correct version of the raspberry pi. I did a quick google and it looks like the newer pi's have slightly different firmware, so I'll update my pi firmware and upload a new image and see if that does the trick. Hopefully will have that up in the next day or so.

**Comment by Khuramsha** [comment]
Thank you so much for your reply; yeah, that's the only explanation I came up with. I will download the new image file in few days—btw great work on OpenSenseRT.

**Comment by pslade2** [comment]
I have updated the image and it works on a new Pi 4B (4GB) that showed your same error previously, so it should be good to go! Let me know if you have any issues. The new image is on the same SimTK page: https://simtk.org/frs/download_confirm.php/file/6411/new_rtk.zip?group_id=2149

**Comment by Khuramsha** [comment]
Thank you for updating the image, I tried the new image file and end up getting a new error, but I think this error is about the board; I looked it up on google and trying to fix it. 
raise NotImplementedError("Board not supported {}".format(board_id))
this is the error I'm getting now. Have you ever dealt with this error before? I've found a solution but am not sure how to implement it.
the solution is to replace the file /usr/local/lib/python3.7/dist-packages/adafruit_platformdetect/constants/boards.py
with the coding from here:
https://github.com/adafruit/Adafruit_Python_PlatformDetect/blob/168ff6b66548e8873d5e05ecbe4f24d2e8b22124/adafruit_platformdetect/constants/boards.py#L395
![error](https://user-images.githubusercontent.com/35789828/131100763-d9017b31-b504-4f2c-b834-3415523791ec.jpg)

**Comment by pslade2** [comment]
Hmmm can you try "sudo pip3 install --upgrade Adafruit-Blinka" and let me know if that fixes things? Maybe the update didn't work for some reason when I did it.

**Comment by Khuramsha** [comment]
Still the same error. Btw, Do I need to connect all the components with pi for the boot? Because right now I'm just using keyboard, mouse and screen. I'm still waiting for my other components to arrive.

**Comment by pslade2** [comment]
When the Pi starts up it automatically tries to run the program, but if the board is not connected it will throw an error. You can hit Ctrl C to kill it and then it should enter the terminal so you can type commands. This Pi doesn't have a user interface just command line, so if you can type commands it has booted. The auto program start is intended so that you don't have to connect the Pi to anything to run the program. Maybe try once you have the components and see if that fixes it!
________________________________

**Comment by Khuramsha** [comment]
Hi, I finally got all of my components, and I followed your direction to connect all the boards. But, I'm still getting the same error. I checked through the "board.py" file and couldn't find the same Pi board like mine, and this is my board information.

![image](https://user-images.githubusercontent.com/35789828/136324661-08725744-226d-40ad-8d45-86bad4f8db89.png)

**Comment by pslade2** [comment]
Glad you got the components! I think the solution you posted before was right, about changing the file /usr/local/lib/python3.7/dist-packages/adafruit_platformdetect/constants/boards.py
Discussion here: https://forums.raspberrypi.com/viewtopic.php?t=307288 

You'll just need to open up the boards.py file at that location and add one line for your revision number 'c03114' under RASPBERRY_PI_4B. Make sure to follow the same formatting as the other lines surrounding it. If you're unfamiliar with editing a file using the command line check this tutorial out: https://linuxize.com/post/how-to-use-nano-text-editor/ 

If adding that to the file doesn't work send me an email and we can have a call so I can help debug: patslade@stanford.edu
