### ISSUE TITLE
Pelvis always has 90 degrees of list even when held stationary

### ISSUE THREAD

**Issue by ruchirK** [pslade2/RealTimeKin#5]
I'm trying to replicate the system and measure 3d kinematics in real time but when I play the results back the animation is always rotated 90 degrees counterclockwise on the frontal plane even when I recorded with just the raspi, case and imus sitting still on my desk.

<img width="1610" alt="Screen Shot 2022-09-23 at 1 11 11 PM" src="https://user-images.githubusercontent.com/4015012/192016117-1d4439fa-0ea1-44ab-abed-614a425934a0.png">

[9-22.zip](https://github.com/pslade2/RealTimeKin/files/9635740/9-22.zip)

The attached zip file has several recordings + raw data dumps. I am using a lsm6ds032 IMU, and when looking straight at the case, the x axis points left, and the y axis points down, and the z axis points into the case, which as I understand it is the correct orientation based on this doc https://simtk-confluence.stanford.edu:8443/display/OpenSim/Wearable+and+Real-time+Kinematics+Estimates+with+OpenSense

Let me know if I can provide any further debugging info. I am adding print lines to the code to see whats going on but I don't quite understand quaternions yet so I'm going pretty slowly with debugging this :)

**Comment by ruchirK** [comment]
And my testing setup looks like this - one IMU for the pelvis + a button off to the side off-camera:

![PXL_20220923_171745893](https://user-images.githubusercontent.com/4015012/192020402-4afd9e12-e677-486d-a84b-a095d67dcef8.jpeg)

I get the same results if the case is lying flat on its back vs standing up on its side. The only other thing I can think of is that I'm using OpenSim 4.4 to visualize the results but the recording was generated for version 4.2?

**Comment by ruchirK** [comment]
Final thing I've observed: when I make a recording with additional imus mounted on my right thigh, shank and foot, the motions of those three segments seems to be visually as expected, just the pelvis is always showing 90 of list the whole time

**Comment by pslade2** [comment]
Hi Ruchir,

That is very interesting. I'll do some digging, but I think you might be right about the different OpenSim versions. Either way, since the kinematics are computed relative to the pelvis, the reported kinematics should all be correct (nothing is provided in the global coordinates for joint angles).

Best,
Patrick

**Comment by ruchirK** [comment]
Hi Patrick,

Thanks for your response! I tried using OpenSim 4.2 earlier which didn't fix the issue for me. I think I found a partial fix though - in `ik_streaming.py` changing

`sensor_to_opensim_rotations = Vec3(-np.pi/2,head_err,0)`

to:

`sensor_to_opensim_rotations = Vec3(0, 0, 0)`

discards the heading error computation (which I'm trying to figure out how to put back) but otherwise seems to resolve the sideways display issue. I believe this makes sense because the pelvis imu's inputs get rotated by `[(0, 0, -1), (0, -1, 0), (-1, 0, 0)]`

So, viewed from behind the pelvis imu's reference frame of: x pointing to the left, y pointing down, and z coming out of the page turns into x going into the page, y pointing up, and z pointing to the right, which aligns with OpenSim's world reference frame. I hope that sentence makes sense it's probably a lot clearer with a visual.

Anyway, hope that's helpful, and hopefully I'm not completely misunderstanding something :) Thanks again for your response and more generally for making such an awesome project!

Best,
Ruchir

**Comment by pslade2** [comment]
Hi Ruchir,

Thanks for debugging that! That makes a lot of sense. I'll make a commit soon to test and resolve that issue.

Glad you like the project, hope it helps you with whatever you're working on!

Best,
Patrick

Best,
Patrick
________________________________
